name: Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: yarn install

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: yarn test
