name: Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: yarn install

      - name: Build
        run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: yarn install

      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: yarn install

      - name: Test
        run: yarn test
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [ 'UTV', 'TST' ]
    outputs:
      env: ${{ steps.env.outputs.env }}
    steps:
      - id: env
        run: echo "env=${{ matrix.environment }}" >> $GITHUB_OUTPUT
      - run: |
          if [[ ${{ steps.env.outputs.env }} == 'UTV' ]]; then exit 0; else exit 1; fi

